AWSTemplateFormatVersion: 2010-09-09

Description: |
  RDS Database for Email Search Application
  
Parameters:

  pDBName:
    Description: Database Name
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/clarusway/dbname'

  pDBPassword:
    Description: Database Password
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/clarusway/password'


Resources:

  rDBSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for MySQL RDS # Required
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: DBSecGrp

  rRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "200"
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: email-application
      DBName: !Ref pDBName
      Engine: mysql
      MasterUserPassword: !Ref pDBPassword
      MasterUsername: admin
      MultiAZ: false
      Port: "3306"
      PubliclyAccessible: true
      VPCSecurityGroups:
      - !GetAtt rDBSecGrp.GroupId
    
